USE [master]
GO

/****** Object:  Database [Avamed]    Script Date: 21/12/2022 1:13:34 pm ******/
CREATE DATABASE [Avamed]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Avamed', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Avamed.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Avamed_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Avamed_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Avamed].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Avamed] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Avamed] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Avamed] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Avamed] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Avamed] SET ARITHABORT OFF 
GO

ALTER DATABASE [Avamed] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Avamed] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Avamed] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Avamed] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Avamed] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Avamed] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Avamed] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Avamed] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Avamed] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Avamed] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Avamed] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Avamed] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Avamed] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Avamed] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Avamed] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Avamed] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Avamed] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Avamed] SET RECOVERY FULL 
GO

ALTER DATABASE [Avamed] SET  MULTI_USER 
GO

ALTER DATABASE [Avamed] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Avamed] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Avamed] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Avamed] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Avamed] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Avamed] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Avamed] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Avamed] SET  READ_WRITE 
GO

